#!/usr/bin/env bash
# deploy-boilerplate.sh
# Build the React boilerplate with an absolute CDN base URL and upload the
# resulting assets to GCS so published sites can load live content.
#
# Usage:
#   ./deploy-boilerplate.sh
#
# Env vars:
#   GCS_BUCKET          — GCS bucket name (default: popkorns-heights)
#   BOILERPLATE_VERSION — version segment inside the bucket (default: v1)
#   BOILERPLATE_KEY     — optional boilerplate identifier (e.g. react-starter,
#                         art-gallery). When set, assets are published under
#                         boilerplate/<key>/<version>/ so several boilerplates
#                         can coexist. When unset, the original
#                         boilerplate/<version>/ layout is used so existing
#                         published sites keep resolving.
#
# The CDN base URL is derived from bucket + key + version, e.g.:
#   https://storage.googleapis.com/popkorns-heights/boilerplate/v1/
#   https://storage.googleapis.com/popkorns-heights/boilerplate/art-gallery/v1/
#
# Publishing a change to an existing version replaces the bundle every live site
# on that version loads. To roll out safely, deploy to a NEW version and move
# sites over deliberately.

set -euo pipefail

BUCKET="${GCS_BUCKET:-popkorns-heights}"
VERSION="${BOILERPLATE_VERSION:-v1}"
KEY="${BOILERPLATE_KEY:-}"

if [[ -n "${KEY}" ]]; then
  REL_PATH="boilerplate/${KEY}/${VERSION}"
else
  REL_PATH="boilerplate/${VERSION}"
fi

GCS_PATH="gs://${BUCKET}/${REL_PATH}"
CDN_BASE="https://storage.googleapis.com/${BUCKET}/${REL_PATH}/"

echo "Boilerplate:  ${KEY:-<legacy, unkeyed>}"
echo "Version:      ${VERSION}"
echo "CDN base:     ${CDN_BASE}"
echo

# Guard against silently replacing a bundle that live sites already load.
if gcloud storage ls "${GCS_PATH}/assets/index.js" > /dev/null 2>&1; then
  echo "WARNING: ${GCS_PATH}/assets/index.js already exists."
  echo "Overwriting it changes every published site on this version immediately."
  read -r -p "Continue? [y/N] " reply
  if [[ ! "${reply}" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
  fi
fi

echo "Building..."
VITE_CDN_BASE="${CDN_BASE}" npm run build

# The shell HTML generated by the API references both of these by exact name,
# so fail loudly if the build did not produce them.
for required in dist/assets/index.js dist/assets/index.css; do
  if [[ ! -f "${required}" ]]; then
    echo "ERROR: expected ${required} to exist after build." >&2
    echo "The published site shell references it by name; aborting." >&2
    exit 1
  fi
done

echo "Uploading assets to ${GCS_PATH}/assets/ ..."
gcloud storage cp -r dist/assets "${GCS_PATH}/"

echo "Setting public-read IAM on uploaded files (if needed)..."
gcloud storage objects update "${GCS_PATH}/assets/**" \
  --add-acl-grant=entity=AllUsers,role=READER 2>/dev/null || true

echo
echo "Done. Boilerplate assets available at:"
echo "  ${CDN_BASE}assets/index.js"
echo "  ${CDN_BASE}assets/index.css"
echo
echo "To point sites at this build, set PUBLISHED_SITES_BOILERPLATE_URL to:"
echo "  ${CDN_BASE%/}"
