import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
    plugins: [react()],
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        },
    },
    // When VITE_CDN_BASE is set at build time, all asset URLs inside the bundle
    // become absolute CDN paths, allowing the bundle to be hosted at a GCS path
    // and loaded from any origin via the thin shell HTML the publishing service
    // generates.
    base: process.env.VITE_CDN_BASE ?? '/',
    build: {
        rollupOptions: {
            output: {
                // Stable (non-hashed) entry filename so the shell HTML can
                // reference a predictable URL without reading a build manifest.
                entryFileNames: 'assets/index.js',
                // The stylesheet needs the same treatment. Vite only links the
                // entry CSS from its generated index.html, which published sites
                // never use — they load a shell generated by the API. Without a
                // predictable name the shell cannot reference the stylesheet and
                // published sites render unstyled.
                //
                // Cache busting comes from the versioned deploy path
                // (/boilerplate/<key>/<version>/assets/...), as it does for index.js.
                assetFileNames: (assetInfo) => {
                    const name = assetInfo.name || '';
                    if (name.endsWith('.css')) return 'assets/index.css';
                    return 'assets/[name]-[hash][extname]';
                },
            },
        },
    },
});
